# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!

# the path to your blog's icon:
favicon: /favicon.png

# the path to manifest.json
manifest: /manifest.json

# show excerpt on post list
show_excerpt: false

# light/dark/auto color scheme
color_scheme: auto

# show floating color theme toggle
show_color_scheme_toggle: true

# uppercase categories
uppercase_categories: true

# capitalize tag names on tags page
capitalize_tags: false

# add hashtag prefix before tags
hashtag_prefix_before_tags: true

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Blog
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Meditations: /meditations
    Links: /links
#    Friends: /friends
#    Projects: /projects
#    About: /about
    # these will be automatically be an icon
    GitHub: https://github.com/ZhuoYun233
    Bilibili: https://space.bilibili.com/12634343
#    WebDAV: 
#    CodePen: https://codepen.io/mrwillcom
#    Patreon: https://www.patreon.com/MrWillCom
#    Mastodon: https://noc.social/@MrWillCom
#    Discord: https://discord.gg/UKuFDjcfY8


# footemeditationsr items
footer:
  # the title
  Blog:
    # the items after the title, display as linksM
    Blog: /
    Archives: /archives
    Meditations: /meditations
    Links: /links
#    Friends: /friends
#    Projects: /projects
#    Resume: /resume
#    About: /about
#    RSS: /atom.xml

  # also the title
  Projects:
    # the items
    AutoReportWin: https://github.com/ZhuoYun233/AutoReportWin
  # the title
  Me:
    # items
    GitHub: https://github.com/ZhuoYun233
    Bilibili: https://space.bilibili.com/12634343
#    Patreon: https://www.patreon.com/MrWillCom
#    Mastodon: https://noc.social/@MrWillCom
#    Discord: https://discord.gg/UKuFDjcfY8
    Email: mailto:zhuoyun233@outlook.com
  ICP:
    鲁ICP备2022002228号-1: https://beian.miit.gov.cn/

# the license your posts under
#license: CC BY-NC 4.0
# the link of your license
#license_link: https://creativecommons.org/licenses/by-nc/4.0

# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!